[package]
name = "wasm-integration-test"
version = "0.0.3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
serde = "1.0"
wasmi = "0.3"
serde_derive = "1.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
holochain_wasm_utils = { path = "../../"}
holochain_core_types_derive = { path = "../../../core_types_derive" }
