[package]
name = "test-bridge-caller"
version = "0.0.3"
authors = ["Holochain Core Dev Team <devcore@holochain.org>"]

[lib]
crate-type = ["cdylib"]

[profile.release]
panic = "abort"

[workspace]
members = []

[dependencies]
serde = "1.0"
serde_json = "1.0"
hdk = { path = "../../hdk-rust" }
serde_derive = "1.0"
holochain_core_types_derive = { path = "../../core_types_derive" }
